[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "francisco-clone"
version = "0.1.0"
description = "AI agent"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "a2a-sdk[http-server]>=0.3.5",
    "loguru>=0.7.3",
    "openai>=1.107.3",
    "uvicorn>=0.35.0",
    "browser-use>=0.7.7",
]
